export const lightTheme = {
  textColor: "var(--text-light)",
  textColorSecondary: "var(--text-light-muted)",
  textContrast: "var(--text-contrast)",
  bgColor: "var(--bg-light-muted)",
  bgColorSecondary: "var(--bg-light)",
  shadowColor: "0deg 0% 59%",
  colorMain: "var(--clr-blue)",
  colorMainMuted: "var(--clr-blue-muted)",
  colorHighlightGreen: "var(--clr-highlight-green)",
  colorHighlightRed: "var(--clr-highlight-red)",
  colorHighlightYellow: "var(--clr-highlight-yellow)",
  colorHighlightBgGreen: "hsl(var(--clr-highlight-bg-green))",
  colorHighlightBgRed: "hsl(var(--clr-highlight-bg-red))",
  colorHighlightBgYellow: "hsl(var(--clr-highlight-bg-yellow))",
};

export const darkTheme = {
  textColor: "var(--text-dark)",
  textColorSecondary: "var(--text-dark-muted)",
  textContrast: "var(--text-contrast)",
  bgColor: "var(--bg-dark)",
  bgColorSecondary: "var(--bg-dark-muted)",
  shadowColor: "240deg 3% 6%",
  colorMain: "var(--clr-blue-light)",
  colorMainMuted: "var(--clr-blue-light-muted)",
  colorHighlightGreen: "var(--clr-highlight-green)",
  colorHighlightRed: "var(--clr-highlight-red)",
  colorHighlightYellow: "var(--clr-highlight-yellow)",
  colorHighlightBgGreen: "hsl(var(--clr-highlight-bg-green-dark) / 0.125)",
  colorHighlightBgRed: "hsl(var(--clr-highlight-bg-red-dark) / 0.125)",
  colorHighlightBgYellow: "hsl(var(--clr-highlight-bg-yellow-dark) / 0.125)",
};
